# Generated by Django 5.0.4 on 2024-04-18 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Kategorie',
                'verbose_name_plural': 'Kategorie',
            },
        ),
        migrations.CreateModel(
            name='Zakaznik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=50)),
                ('prijmeni', models.CharField(max_length=50)),
                ('telefon', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('heslo', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Zakaznik',
                'verbose_name_plural': 'Zakaznici',
            },
        ),
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=50)),
                ('cena', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('popis', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('fotka', models.ImageField(upload_to='uploads/product/')),
                ('je_akce', models.BooleanField(default=False)),
                ('akce_cena', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('kategorie', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Eshop.kategorie')),
            ],
            options={
                'verbose_name': 'Produkt',
                'verbose_name_plural': 'Produkty',
            },
        ),
        migrations.CreateModel(
            name='Objednavka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pocet', models.IntegerField(default=1)),
                ('adresa', models.CharField(blank=True, default='', max_length=100)),
                ('telefon', models.CharField(blank=True, default='', max_length=20)),
                ('datum', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('produkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Eshop.produkt')),
                ('zakaznik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Eshop.zakaznik')),
            ],
            options={
                'verbose_name': 'Objednavka',
                'verbose_name_plural': 'Objednavky',
            },
        ),
    ]
