# Generated by Django 5.0.4 on 2024-04-18 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategorie',
            name='nazev',
            field=models.CharField(max_length=50, unique=True, verbose_name='Název kategorie'),
        ),
        migrations.AlterField(
            model_name='objednavka',
            name='adresa',
            field=models.CharField(blank=True, default='', help_text='Zadejte adresu zakazníka', max_length=100, verbose_name='Adresa'),
        ),
        migrations.AlterField(
            model_name='objednavka',
            name='datum',
            field=models.DateField(auto_now_add=True, help_text='Datum objednávky', verbose_name='Datum'),
        ),
        migrations.AlterField(
            model_name='objednavka',
            name='pocet',
            field=models.IntegerField(default=1, help_text='Zadejte počet produktů', verbose_name='Počet'),
        ),
        migrations.AlterField(
            model_name='objednavka',
            name='produkt',
            field=models.ForeignKey(help_text='Vyberte produkt', on_delete=django.db.models.deletion.CASCADE, to='Eshop.produkt', verbose_name='Produkt'),
        ),
        migrations.AlterField(
            model_name='objednavka',
            name='status',
            field=models.BooleanField(default=False, help_text='Zaškrtněte pokud je objednávka vyřízena', verbose_name='Stav'),
        ),
        migrations.AlterField(
            model_name='objednavka',
            name='telefon',
            field=models.CharField(blank=True, default='', help_text='Zadejte telefonní číslo zakazníka', max_length=20, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='objednavka',
            name='zakaznik',
            field=models.ForeignKey(help_text='Vyberte zakazníka', on_delete=django.db.models.deletion.CASCADE, to='Eshop.zakaznik', verbose_name='Zakaznik'),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='akce_cena',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Zadejte akční cenu produktu v kč', max_digits=10, verbose_name='Akční cena'),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='cena',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Zadejte cenu prodoktu v kč', max_digits=10, verbose_name='Cena produktu'),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='fotka',
            field=models.ImageField(help_text='Vyberte fotku produktu', upload_to='fotky/produkty/', verbose_name='Fotka produktu'),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='je_akce',
            field=models.BooleanField(default=False, help_text='Zaškrtněte pokud je produkt v akci', verbose_name='Je produkt v akci'),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='kategorie',
            field=models.ForeignKey(default=1, help_text='Vyberte kategorii produktu', on_delete=django.db.models.deletion.CASCADE, to='Eshop.kategorie', verbose_name='Kategorie produktu'),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='nazev',
            field=models.CharField(max_length=50, unique=True, verbose_name='Název produktu'),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='popis',
            field=models.CharField(blank=True, default='', help_text='Zadejte popis produktu - max 500 znaků', max_length=500, null=True, verbose_name='Popis produktu'),
        ),
        migrations.AlterField(
            model_name='zakaznik',
            name='email',
            field=models.EmailField(help_text='Zadejte email zakazníka', max_length=100, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='zakaznik',
            name='heslo',
            field=models.CharField(help_text='Zadejte heslo', max_length=50, verbose_name='Heslo'),
        ),
        migrations.AlterField(
            model_name='zakaznik',
            name='jmeno',
            field=models.CharField(help_text='Zadejte jméno zakazníka', max_length=50, verbose_name='Jméno'),
        ),
        migrations.AlterField(
            model_name='zakaznik',
            name='prijmeni',
            field=models.CharField(help_text='Zadejte příjmení zakazníka', max_length=50, verbose_name='Příjmení'),
        ),
        migrations.AlterField(
            model_name='zakaznik',
            name='telefon',
            field=models.CharField(blank=True, default='', help_text='Zadejte telefonní číslo zakazníka', max_length=20, verbose_name='Telefon'),
        ),
    ]
