# Generated by Django 5.0.4 on 2024-04-18 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop', '0002_alter_kategorie_nazev_alter_objednavka_adresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategorie',
            name='nazev',
            field=models.CharField(help_text='Vytvořte novou kategorii', max_length=50, unique=True, verbose_name='Název kategorie'),
        ),
    ]
