# Generated by Django 5.0.4 on 2024-04-18 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop', '0003_alter_kategorie_nazev'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkt',
            name='akce_cena',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Zadejte akční cenu produktu v kč/m³', max_digits=10, verbose_name='Akční cena'),
        ),
    ]
