# Generated by Django 5.0.4 on 2024-04-19 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop', '0004_alter_produkt_akce_cena'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='closeup_fotka',
            field=models.ImageField(blank=True, help_text='Vyberte fotku z dálky', upload_to='fotky/produkty/', verbose_name='Fotka produktu v bytě'),
        ),
    ]
