# Generated by Django 5.0.4 on 2024-04-19 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop', '0006_alter_produkt_closeup_fotka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkt',
            name='closeup_fotka',
            field=models.ImageField(help_text='Vyberte fotku z dálky', upload_to='fotky/closeup/', verbose_name='Fotka produktu v bytě'),
        ),
    ]
