# Generated by Django 5.0.4 on 2024-04-19 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop', '0007_alter_produkt_closeup_fotka'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='barva',
            field=models.CharField(choices=[('černá', 'Černá'), ('světlá', 'Světlá'), ('hnědá', 'Hnědá'), ('šedá', 'Šedá')], default='světlá', max_length=50, verbose_name='Barva'),
        ),
        migrations.AddField(
            model_name='produkt',
            name='material',
            field=models.CharField(choices=[('dub', 'Dub'), ('buk', 'Buk'), ('smrk', 'Smrk'), ('javor', 'Javor')], default='dub', max_length=50, verbose_name='Materiál'),
        ),
    ]
