# Generated by Django 5.0.4 on 2024-04-19 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop', '0010_remove_produkt_nazev_produkt_nazev_produktu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produkt',
            name='nazev_produktu',
        ),
        migrations.AddField(
            model_name='produkt',
            name='nazev',
            field=models.CharField(default='Default Name', max_length=50, unique=True, verbose_name='Název produktu'),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='kategorie',
            field=models.ForeignKey(default=1, help_text='Vyberte kategorii produktu', on_delete=django.db.models.deletion.CASCADE, to='Eshop.kategorie', verbose_name='Kategorie produktu'),
        ),
    ]
