# Generated by Django 5.0.4 on 2024-04-19 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop', '0011_remove_produkt_nazev_produktu_produkt_nazev_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkt',
            name='nazev',
            field=models.CharField(default='Podlaha', max_length=50, verbose_name='Název produktu'),
        ),
    ]
