# Generated by Django 5.0.4 on 2024-04-19 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop', '0012_alter_produkt_nazev'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='zeme_puvodu',
            field=models.CharField(choices=[('Česká republika', 'Česká republika'), ('Slovensko', 'Slovensko'), ('Polsko', 'Polsko'), ('Německo', 'Německo'), ('Rakousko', 'Rakousko'), ('Švýcarsko', 'Švýcarsko'), ('Estonsko', 'Estonsko')], default='Česká republika', max_length=50, verbose_name='Země původu'),
        ),
    ]
