# Generated by Django 5.0.4 on 2024-04-19 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop', '0013_produkt_zeme_puvodu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkt',
            name='cena',
            field=models.PositiveSmallIntegerField(default=800, help_text='Zadejte cenu prodoktu v kč', verbose_name='Cena produktu'),
        ),
    ]
