# Generated by Django 5.0.4 on 2024-04-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop', '0014_alter_produkt_cena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkt',
            name='material',
            field=models.CharField(choices=[('dub', 'Dub'), ('buk', 'Buk'), ('smrk', 'Smrk'), ('javor', 'Javor'), ('bříza', 'Bříza'), ('jedle', 'Jedle'), ('borovice', 'Borovice'), ('akát', 'Akát'), ('mahagon', 'Mahagon'), ('bambus', 'Bambus'), (' ', ' ')], default=' ', max_length=50, verbose_name='Materiál'),
        ),
    ]
