# Generated by Django 5.0.4 on 2024-04-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop', '0016_remove_produkt_zeme_puvodu_alter_produkt_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkt',
            name='cena',
            field=models.PositiveSmallIntegerField(default=800, help_text='Zadejte cenu produktu v Kč/m²', verbose_name='Cena produktu'),
        ),
    ]
