# Generated by Django 5.0.4 on 2024-04-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop', '0019_alter_produkt_cena_alter_produkt_nazev'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkt',
            name='barva',
            field=models.CharField(choices=[('černá', 'Černá'), ('světlá', 'Světlá'), ('hnědá', 'Hnědá'), ('šedá', 'Šedá'), ('světle šedá', 'Světle šedá'), ('tmavě šedá', 'Tmavě šedá'), ('béžová', 'Béžová')], default='světlá', max_length=50, verbose_name='Barva'),
        ),
    ]
