# Generated by Django 5.0.4 on 2024-04-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop', '0022_alter_produkt_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkt',
            name='barva',
            field=models.CharField(choices=[('černá', 'Černá'), ('světlá', 'Světlá'), ('hnědá', 'Hnědá'), ('šedá', 'Šedá'), ('světle šedá', 'Světle šedá'), ('tmavě šedá', 'Tmavě šedá'), ('béžová', 'Béžová'), ('světle béžová', 'Světle béžová'), ('akátová', 'Akátová')], default='světlá', max_length=50, verbose_name='Barva'),
        ),
    ]
