# Generated by Django 5.0.4 on 2024-04-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop', '0026_alter_produkt_barva'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='cena_ostatni',
            field=models.PositiveSmallIntegerField(blank='True', default=0, verbose_name='Cena ostatních produktů'),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='barva',
            field=models.CharField(blank='True', choices=[('', ''), ('černá', 'Černá'), ('světlá', 'Světlá'), ('hnědá', 'Hnědá'), ('šedá', 'Šedá'), ('světle šedá', 'Světle šedá'), ('tmavě šedá', 'Tmavě šedá'), ('béžová', 'Béžová'), ('světle béžová', 'Světle béžová'), ('akátová', 'Akátová')], default=' ', max_length=50, verbose_name='Barva'),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='cena',
            field=models.DecimalField(blank='True', decimal_places=2, default=800, help_text='Zadejte cenu produktu v Kč/m - Pouze u podlah²', max_digits=10, verbose_name='Cena produktu'),
        ),
    ]
