# Generated by Django 5.0.4 on 2024-04-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop', '0027_produkt_cena_ostatni_alter_produkt_barva_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produkt',
            name='cena_ostatni',
        ),
        migrations.AlterField(
            model_name='produkt',
            name='cena',
            field=models.DecimalField(blank='True', decimal_places=2, default=0, help_text='Zadejte cenu produktu v Kč/m - Pouze u podlah', max_digits=10, verbose_name='Cena produktu'),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='material',
            field=models.CharField(blank='True', choices=[(' ', ' '), ('dub', 'Dub'), ('buk', 'Buk'), ('smrk', 'Smrk'), ('javor', 'Javor'), ('bříza', 'Bříza'), ('jedle', 'Jedle'), ('borovice', 'Borovice'), ('akát', 'Akát'), ('mahagon', 'Mahagon'), ('bambus', 'Bambus'), ('jasan', 'Jasan')], default=' ', max_length=50, verbose_name='Materiál'),
        ),
    ]
