# Generated by Django 5.0.4 on 2024-04-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop', '0028_remove_produkt_cena_ostatni_alter_produkt_cena_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkt',
            name='barva',
            field=models.CharField(blank='True', choices=[('', ''), ('černá', 'Černá'), ('světlá', 'Světlá'), ('hnědá', 'Hnědá'), ('šedá', 'Šedá'), ('světle šedá', 'Světle šedá'), ('tmavě šedá', 'Tmavě šedá'), ('béžová', 'Béžová'), ('světle béžová', 'Světle béžová'), ('akátová', 'Akátová')], max_length=50, verbose_name='Barva'),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='material',
            field=models.CharField(blank='True', choices=[(' ', ' '), ('dub', 'Dub'), ('buk', 'Buk'), ('smrk', 'Smrk'), ('javor', 'Javor'), ('bříza', 'Bříza'), ('jedle', 'Jedle'), ('borovice', 'Borovice'), ('akát', 'Akát'), ('mahagon', 'Mahagon'), ('bambus', 'Bambus'), ('jasan', 'Jasan')], max_length=50, verbose_name='Materiál'),
        ),
    ]
