# Generated by Django 5.0.4 on 2024-04-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop', '0030_alter_produkt_cena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkt',
            name='cena',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Zadejte cenu produktu v Kč/m² - Pouze u podlah| Ostatně Kč/ks', max_digits=10, verbose_name='Cena produktu'),
        ),
    ]
