# Generated by Django 5.0.4 on 2024-04-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop', '0032_alter_produkt_cena'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategorie',
            name='popis',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Popis kategorie'),
        ),
    ]
