# Generated by Django 5.0.4 on 2024-04-19 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop', '0033_kategorie_popis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(choices=[('nizza', 'Nizza'), ('zen', 'Zen'), ('dublin', 'Dublin'), ('kahrs', 'Kahrs'), ('triumph', 'Triumph'), ('soldline', 'Soldline')], max_length=50, verbose_name='Jméno brandu')),
                ('popis', models.CharField(default='', max_length=500, verbose_name='Popis brandu')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brandy',
            },
        ),
        migrations.RemoveField(
            model_name='produkt',
            name='nazev',
        ),
        migrations.AddField(
            model_name='produkt',
            name='nazev',
            field=models.ManyToManyField(help_text='Brand = název produktu', to='Eshop.brand', verbose_name='Název produktu'),
        ),
    ]
