# Generated by Django 5.0.4 on 2024-04-19 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop', '0034_brand_remove_produkt_nazev_produkt_nazev'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='specifikace',
            field=models.CharField(choices=[('koberce', 'Koberec'), ('vinyl', 'Vinylové podlahy'), ('drevo', 'Dřevěné podlahy'), ('laminat', 'Laminátové podlahy')], default=1, max_length=50, verbose_name='Specifikace'),
            preserve_default=False,
        ),
    ]
