# Generated by Django 5.0.4 on 2024-04-19 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop', '0035_brand_specifikace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='specifikace',
            field=models.CharField(choices=[('', ''), ('koberce', 'Koberec'), ('vinyl', 'Vinylové podlahy'), ('drevo', 'Dřevěné podlahy'), ('laminat', 'Laminátové podlahy')], default='', max_length=50, verbose_name='Specifikace'),
        ),
    ]
