# Generated by Django 5.0.4 on 2024-04-19 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop', '0037_alter_brand_nazev'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='nazev',
            field=models.CharField(choices=[('nizza', 'Nizza'), ('zen', 'Zen'), ('dublin', 'Dublin'), ('kahrs', 'Kahrs'), ('triumph', 'Triumph'), ('soldline', 'Soldline')], max_length=50, verbose_name='Jméno brandu'),
        ),
    ]
