# Generated by Django 5.0.4 on 2024-04-20 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop', '0040_rename_specifikace_brand_odvetvi'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategorie',
            name='nazev_jednotneCislo',
            field=models.TextField(max_length=50, null=True, verbose_name='Název kategorie v jednotném čísle'),
        ),
    ]
