# Generated by Django 5.0.4 on 2024-04-20 09:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop', '0043_produkt_baleni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkt',
            name='baleni',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Zadejte počet metrů čtverečních v balení', max_digits=10, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(7)], verbose_name='Obsah balení'),
        ),
    ]
