# Generated by Django 5.0.4 on 2024-04-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop', '0044_alter_produkt_baleni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkt',
            name='cena',
            field=models.PositiveIntegerField(help_text='Zadejte cenu produktu v Kč/m² - Pouze u podlah| Ostatně Kč/ks', verbose_name='Cena produktu'),
        ),
    ]
