# Generated by Django 5.0.4 on 2024-04-20 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop', '0046_recenze'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recenze',
            options={'verbose_name': 'Recenze', 'verbose_name_plural': 'Recenze'},
        ),
    ]
