# Generated by Django 5.0.4 on 2024-04-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Eshop", "0047_alter_recenze_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produkt",
            name="material",
            field=models.CharField(
                blank="True",
                choices=[
                    (" ", " "),
                    ("syntetický", "Syntetický"),
                    ("dub", "Dub"),
                    ("buk", "Buk"),
                    ("smrk", "Smrk"),
                    ("javor", "Javor"),
                    ("bříza", "Bříza"),
                    ("jedle", "Jedle"),
                    ("borovice", "Borovice"),
                    ("akát", "Akát"),
                    ("mahagon", "Mahagon"),
                    ("bambus", "Bambus"),
                    ("jasan", "Jasan"),
                ],
                max_length=50,
                verbose_name="Materiál",
            ),
        ),
    ]
