# Generated by Django 5.0.4 on 2024-04-22 01:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Eshop", "0051_alter_produkt_material"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recenze",
            name="text",
            field=models.TextField(
                validators=[
                    django.core.validators.MinLengthValidator(
                        25, message="Recenze musí být alespoň 25 znaků dlouhá."
                    ),
                    django.core.validators.MaxLengthValidator(
                        100, message="Recenze nesmí překročit 100 znaků."
                    ),
                ]
            ),
        ),
    ]
