# Generated by Django 5.0.4 on 2024-04-22 02:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Eshop", "0052_alter_recenze_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recenze",
            name="hodnoceni",
            field=models.IntegerField(
                choices=[(1, "*"), (2, "**"), (3, "***"), (4, "****"), (5, "*****")],
                default=3,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
