# Generated by Django 5.0.4 on 2024-04-22 02:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Eshop", "0053_alter_recenze_hodnoceni"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hodnoceni",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hodnoceni",
                    models.IntegerField(
                        choices=[
                            (1, "*"),
                            (2, "**"),
                            (3, "***"),
                            (4, "****"),
                            (5, "*****"),
                        ],
                        default=3,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "Hodnoceni",
                "verbose_name_plural": "Hodnoceni",
            },
        ),
        migrations.AlterField(
            model_name="recenze",
            name="hodnoceni",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Eshop.hodnoceni"
            ),
        ),
    ]
