# Generated by Django 5.0.4 on 2024-04-22 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Eshop", "0055_alter_recenze_hodnoceni_delete_hodnoceni"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produkt",
            name="akce_cena",
        ),
        migrations.RemoveField(
            model_name="produkt",
            name="je_akce",
        ),
    ]
