# Generated by Django 5.0.4 on 2024-04-22 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Eshop", "0056_remove_produkt_akce_cena_remove_produkt_je_akce"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recenze",
            name="hodnoceni",
        ),
    ]
