# Generated by Django 5.0.4 on 2024-04-22 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Eshop", "0057_remove_recenze_hodnoceni"),
    ]

    operations = [
        migrations.AddField(
            model_name="recenze",
            name="hodnoceni",
            field=models.IntegerField(
                choices=[(1, "*"), (2, "**"), (3, "***"), (4, "****"), (5, "*****")],
                default=5,
            ),
        ),
    ]
